language: scala

# so travis finds the tags
install:
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --unshallow --tags

scala:
  - "2.10.7"
  - "2.11.12"
  - "2.12.6"
  - "2.13.0-M4"

jdk:
  - oraclejdk8

node_js:
  - "6"

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

# workaround for travis-ci #7703
before_script:
   - sudo chmod +x /usr/local/bin/sbt

after_success:
  - '[[ $TRAVIS_BRANCH == "master" ]] && { sbt  ++$TRAVIS_SCALA_VERSION publish; };'

env:
  global:
  - secure: DW4OXvjLG04G/k4dPSvOoHOEZ081GLBXP45RbOqGTuC1Kkvi1mOZeOEgPWMfLhimwUxkn3p+6EoddXweXvrcbx7GxR0yazSGGMw8OEeHITPE9c9sfvxXcJkufL+JG+mWiNB5qofaYTogM6QxTlrpIiKY1qHOz/u+gqakGKp4GBM=
  - secure: uWZPYz7Q02Vw7y1pHRKUiJ5oe20m1LJc7UIDQEEEjCxQ92pwlAwoCYWBzr0eaP7bmCJNpvLxIZWa6jPeYZ++HM++nQHewsHpqgVyw1WQ33jQZTlENe3raoPdFpyPrDPE7C2JMIp6QH5g+9zD3m4mdTvKcfTFdYLgKFZNhCWIAV8=

